sudo: required

services:
  - docker

install:
  - ./prepareEnv.sh
  - docker-compose up -d
  - docker exec envtester_tester-php_1 composer install

script: docker exec envtester_tester-php_1 /app/runTests.sh
