version: '2'

services:

  projects-service-nginx:
    image: nginx:1.11
    ports:
      - "8001:80"
    volumes:
      - ./services/ProjectsService/:/app
      - ./services/ProjectsService/var/log:/var/log
      - ./ProjectsService.conf:/etc/nginx/conf.d/default.conf
    links:
      - projects-service-php
    networks:
      - code-network

  projects-service-php:
    build: ./services/ProjectsService
    links:
      - projects-service-mysql
      - projects-service-rabbitmq
    volumes:
      - ./services/ProjectsService/:/app
      - ./services/ProjectsService/var/log:/var/log/php
    environment:
      RABBIT_HOST: 'projects-service-rabbitmq'
      RABBIT_PORT: '5672'
      RABBIT_LOGIN: 'guest'
      RABBIT_PASSWORD: 'guest'
      RABBIT_CHANNEL: 'events'

      MYSQL_HOST: 'projects-service-mysql'
      MYSQL_PORT: '3306'
      MYSQL_LOGIN: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: 'testdb'
    networks:
      - code-network

  projects-service-installer:
    build: ./services/ProjectsService
    links:
      - projects-service-mysql
      - projects-service-rabbitmq
    volumes:
      - ./services/ProjectsService/:/app
      - ./services/ProjectsService/var/log:/var/log/php
    environment:
      RABBIT_HOST: 'projects-service-rabbitmq'
      RABBIT_PORT: '5672'
      RABBIT_LOGIN: 'guest'
      RABBIT_PASSWORD: 'guest'
      RABBIT_CHANNEL: 'events'

      MYSQL_HOST: 'projects-service-mysql'
      MYSQL_PORT: '3306'
      MYSQL_LOGIN: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: 'testdb'
    networks:
      - code-network
    command: "php /app/install.php"

  projects-service-mysql:
    image: mysql:8.0.1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testdb
    networks:
      - code-network

  projects-service-rabbitmq:
    image: rabbitmq:3.6.10
    networks:
      - code-network

networks:
    code-network:
        driver: bridge
